baseurl: /jekyll-flashcards

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge

include: ["_decks"]

collections:
  decks:
    output: true

defaults:
  - scope:
      path: "_decks"
    values:
      layout: deck